<h1>Задание 1. Проекционные методы решения краевой задачи для ОДУ второго порядка</h1>
<h2 align = "center"><font color="#6f8600">Вариант 8</font></h2>
<p>Будем искать решение следующей задачи:</p>
$-\frac{4-x}{5-2x}u''+ \frac{1-x}{2}u' +\frac{1}{2}ln(3+x)*u  = 1 + \frac{x}{3}, u(-1) = u(1) = 0$
<p>методами:</p>
<ol>
<li>Галеркина</li>
<li>Коллокации</li>
</ol>

<p>Точное решение y* ОДУ, полученным обращением к MATLAB: </p>
<table>
<thead>
<tr>
	<th>x</th>
	<th>y*</th>
</tr>
</thead>
<tbody>
    <tr>
        <td>-1</td>
        <td>0</td>
    </tr>
    <tr>
        <td>-0.5</td>
        <td>0.2738</td>
    </tr>
    <tr>
        <td>0</td>
        <td>0.4267</td>
    </tr>
    <tr>
        <td>0,5</td>
        <td>0.3605</td>
    </tr>
    <tr>
        <td>1</td>
        <td>0</td>
    </tr>
</tbody>
</table>

<h3>Метод Галеркина</h3>
<p>Координатная система: </p>
$\omega_{i}(x) = (1 - x^{2})P_{i}^{(1,1)}(x), где\ \ i = 0,1,\dots$ - ЛНЗ система
<p>На левом конце промежутка [−1, 1] краевая задача будет называться первой, так как $\alpha_{2} = 0 \Rightarrow Q_{l} = 0$</p>
<p>На правом конце промежутка [−1, 1] краевая задача будет называться первой, так как $\beta_{2} = 0 \Rightarrow Q_{r} = 0$</p>
<p>Приближенное решение ищется в виде линейной комбинации $\omega_{i}$ и коэффициентов $c_{i}$ : $y^{n}(x) = \sum\limits_{i=1}^n c_{i}\omega_{i}$, где $c_{i}$ находятся из системы линейных уравнений: $\sum\limits_{j=1}^n (L\omega_{j}, \omega_{i})c_{j} = (f,\omega_{i})$, $i = 1, 2, \dots, n$</p>

In [217]:
import sympy as sp
import math
import pandas as pd
import numpy as np

x = sp.Symbol("x")
y_matlab = [0.2738, 0.4267, 0.3605]

# Подготовка таблицы вывода
n = [3, 4, 5, 6, 7]
condA = []
leftFoundValue = []
middleFoundValue = []
rightFoundValue = []
leftDiffValue = []
middleDiffValue = []
rightDiffValue = []

<h5>Реализация метода Галеркина</h5>

In [218]:
#     Создадим список координатных функций
[coordFunctions, diffCoordFunctions] = createcoordFunctions(7)

#     Создадим список значений на функционале
L = countL(coordFunctions, diffCoordFunctions)

#     Вычислим расширенную матрицу системы
[A, b] = matrixCoeff(7, coordFunctions, L)

for i in n: 
    print(f"Матрица A[{i},{i}]")
    print(A[:i, :i])
    
    print(f"Вектор b[{i},1]")
    print(b[:i,:1])
    
    c = countCoeff(A, b, i)
    
    print(f"Коэффициенты c_i разложения приближенного решения по координатным функциям")
    print(c)
    print()
    condA.append(np.linalg.cond(A[:i, :i], np.inf))
    
    yLeft = 0;yMiddle = 0;yRight = 0;
    for j in range(i):
        yLeft += coordFunctions[j].subs(x, sp.simplify(-1/2))*c[j];
        yMiddle += coordFunctions[j].subs(x, sp.simplify(0))*c[j];
        yRight += coordFunctions[j].subs(x, sp.simplify(1/2))*c[j];
    leftFoundValue.append(yLeft)
    leftDiffValue.append(y_matlab[0]-yLeft)
    middleFoundValue.append(yMiddle)
    middleDiffValue.append(y_matlab[1]-yMiddle)
    rightFoundValue.append(yRight)
    rightDiffValue.append(y_matlab[2]-yRight)

Матрица A[3,3]
[[ 3.00914195  0.99771417 -0.3231749 ]
 [-0.34424599  5.74610509  1.44889857]
 [ 0.12539309 -0.29111173  8.849551  ]]
Вектор b[3,1]
[[1.33333333]
 [0.17777778]
 [0.        ]]
Коэффициенты c_i разложения приближенного решения по координатным функциям
[[ 0.42363501]
 [ 0.05735641]
 [-0.00411589]]

Матрица A[4,4]
[[ 3.00914195  0.99771417 -0.3231749   0.02865837]
 [-0.34424599  5.74610509  1.44889857 -0.29090203]
 [ 0.12539309 -0.29111173  8.849551    1.81360501]
 [-0.0123139   0.26087245 -0.12334164 12.04144875]]
Вектор b[4,1]
[[1.33333333]
 [0.17777778]
 [0.        ]
 [0.        ]]
Коэффициенты c_i разложения приближенного решения по координатным функциям
[[ 0.42368878]
 [ 0.05727376]
 [-0.00394559]
 [-0.00084795]]

Матрица A[5,5]
[[ 3.00914195e+00  9.97714167e-01 -3.23174902e-01  2.86583740e-02
   1.42376374e-02]
 [-3.44245994e-01  5.74610509e+00  1.44889857e+00 -2.90902025e-01
   4.92459896e-02]
 [ 1.25393091e-01 -2.91111735e-01  8.84955100e+00  1.81360501e+00
  -2.3459

<h5>Таблица результатов метода Галеркина</h5>

In [121]:
df = pd.DataFrame({'n': [n[0], n[1], n[2], n[3], n[4]], 
                   'cond(A)': [condA[0], condA[1], condA[2], condA[3], condA[4]], 
                   'y_n(-0.5)': [leftFoundValue[0], leftFoundValue[1], leftFoundValue[2], leftFoundValue[3], leftFoundValue[4]], 
                   'y_n(0)': [middleFoundValue[0], middleFoundValue[1], middleFoundValue[2], middleFoundValue[3], middleFoundValue[4]], 
                   'y_n(0.5)': [rightFoundValue[0], rightFoundValue[1], rightFoundValue[2], rightFoundValue[3], rightFoundValue[4]],
                   '(y*-y_n)(-0.5)': [leftDiffValue[0], leftDiffValue[1], leftDiffValue[2], leftDiffValue[3], leftDiffValue[4]], 
                   '(y*-y_n)(0)': [middleDiffValue[0], middleDiffValue[1], middleDiffValue[2], middleDiffValue[3], middleDiffValue[4]], 
                   '(y*-y_n)(0.5)': [rightDiffValue[0], rightDiffValue[1], rightDiffValue[2], rightDiffValue[3], rightDiffValue[4]], 
                  })
df

n   cond(A)            y_n(-0.5)               y_n(0)             y_n(0.5)  \
0  3  3.719784  [0.274130155800084]  [0.426721928158804]  [0.360164765826143]   
1  4  5.054221  [0.274130155800084]  [0.426721928158804]  [0.360564530067648]   
2  5  6.407271  [0.273858939076262]  [0.426647973973330]  [0.360540779090871]   
3  6  7.871985  [0.273829369059957]  [0.426677402276716]  [0.360540202192694]   
4  7  9.342647  [0.273831645295096]  [0.426676483507909]  [0.360539629490761]   

            (y*-y_n)(-0.5)             (y*-y_n)(0)           (y*-y_n)(0.5)  
0  [-0.000330155800084164]  [-2.19281588041964e-5]  [0.000335234173857446]  
1   [-5.89390762619213e-5]   [5.20260266704264e-5]  [-6.45300676482274e-5]  
2   [-2.93690599567076e-5]   [2.25977232842234e-5]  [-4.07790908709127e-5]  
3   [-3.16452950957502e-5]   [2.35164920905362e-5]  [-4.02021926942386e-5]  
4   [-3.11443436795122e-5]   [2.27149189047648e-5]  [-3.96294907608064e-5]

<h3>Метод Коллокации</h3>
<p>Выберем некоторую систему точек $−1 \leqslant t_{1} < t_{2} < \dots < t_{n} \leqslant 1$, называемых
узлами коллокации, и будем строить приближенное решение по формуле $\sum\limits_{j=1}^n (L\omega_{j}|_{x=t_{i}})c_{j} = f(t_{i})$, $i = 1, 2, \dots, n$</p>
<p>В качестве узлов коллокации будем брать узлы многочлена Чебышева первого рода.</p>

In [146]:
# Подготовка таблицы вывода
condA = []
leftFoundValue = []
middleFoundValue = []
rightFoundValue = []
leftDiffValue = []
middleDiffValue = []
rightDiffValue = []

<h5>Реализация метода Коллокации</h5>

In [148]:
#     Создадим список координатных функций
[coordFunctions, diffCoordFunctions] = createcoordFunctions(7)

#     Создадим список значений на функционале
L = countL(coordFunctions, diffCoordFunctions)

for i in n: 
#     Вычислим расширенную матрицу системы
    [A, b] = collocMatrixCoeff(i, coordFunctions, L)
    
    print(f"Матрица A[{i},{i}]")
    print(A[:i, :i])
    
    print(f"Вектор b[{i},1]")
    print(b[:i,:1])
    
    c = countCoeff(A, b, i)
    print(f"Коэффициенты c_i разложения приближенного решения по координатным функциям")
    print(c)
    print()
    
    condA.append(np.linalg.cond(A[:i, :i], np.inf))
    
    yLeft = 0;yMiddle = 0;yRight = 0
    for j in range(i):
        yLeft += coordFunctions[j].subs(x, sp.simplify(-1/2))*c[j];
        yMiddle += coordFunctions[j].subs(x, sp.simplify(0))*c[j];
        yRight += coordFunctions[j].subs(x, sp.simplify(1/2))*c[j];
    leftFoundValue.append(yLeft)
    leftDiffValue.append(y_matlab[0]-yLeft)
    middleFoundValue.append(yMiddle)
    middleDiffValue.append(y_matlab[1]-yMiddle)
    rightFoundValue.append(yRight)
    rightDiffValue.append(y_matlab[2]-yRight)

Матрица A[3,3]
[[  1.97100989  10.09155383  23.95342817]
 [  2.14930614   1.          -7.61197961]
 [  3.15640312 -10.00835148  19.90311117]]
Вектор b[3,1]
[[1.28867513]
 [1.        ]
 [0.71132487]]
Коэффициенты c_i разложения приближенного решения по координатным функциям
[[ 0.42500933]
 [ 0.05463324]
 [-0.00418966]]

Матрица A[4,4]
[[  1.98147994  10.88500226  28.81130802  53.80614104]
 [  1.99230673   4.66693091  -1.35944571 -13.10626041]
 [  2.46010156  -3.02993482  -3.71432477  12.24475653]
 [  3.26902215 -11.07314254  24.65833346 -42.45476623]]
Вектор b[4,1]
[[1.30795984]
 [1.12756114]
 [0.87243886]
 [0.69204016]]
Коэффициенты c_i разложения приближенного решения по координатным функциям
[[ 0.42362206]
 [ 0.05729299]
 [-0.00381365]
 [-0.00084   ]]

Матрица A[5,5]
[[  1.98745585  11.27328564  31.26901584  62.46659382 101.95525096]
 [  1.96021576   6.76961814   6.53203348  -5.58580699 -22.34898737]
 [  2.14930614   1.          -7.61197961  -1.5         15.34331634]
 [  2.70722403  

<h5>Таблица результатов метода Коллокации</h5>

In [149]:
df = pd.DataFrame({'n': [n[0], n[1], n[2], n[3], n[4]], 
                   'cond(A)': [condA[0], condA[1], condA[2], condA[3], condA[4]], 
                   'y_n(-0.5)': [leftFoundValue[0], leftFoundValue[1], leftFoundValue[2], leftFoundValue[3], leftFoundValue[4]], 
                   'y_n(0)': [middleFoundValue[0], middleFoundValue[1], middleFoundValue[2], middleFoundValue[3], middleFoundValue[4]], 
                   'y_n(0.5)': [rightFoundValue[0], rightFoundValue[1], rightFoundValue[2], rightFoundValue[3], rightFoundValue[4]],
                   '(y*-y_n)(-0.5)': [leftDiffValue[0], leftDiffValue[1], leftDiffValue[2], leftDiffValue[3], leftDiffValue[4]], 
                   '(y*-y_n)(0)': [middleDiffValue[0], middleDiffValue[1], middleDiffValue[2], middleDiffValue[3], middleDiffValue[4]], 
                   '(y*-y_n)(0.5)': [rightDiffValue[0], rightDiffValue[1], rightDiffValue[2], rightDiffValue[3], rightDiffValue[4]], 
                  })
df

n     cond(A)            y_n(-0.5)               y_n(0)  \
0  3   15.643304  [0.277192896859212]  [0.428151572335284]   
1  4   41.385308  [0.273816763933731]  [0.426482295933182]   
2  5   90.580315  [0.273849009213993]  [0.426689302589433]   
3  6  174.166882  [0.273833797906172]  [0.426674074351672]   
4  7  305.251035  [0.273831019548330]  [0.426677334248152]   

              y_n(0.5)          (y*-y_n)(-0.5)             (y*-y_n)(0)  \
0  [0.359142752842653]  [-0.00339289685921157]  [-0.00145157233528376]   
1  [0.360543740114219]  [-1.67639337307346e-5]  [0.000217704066818203]   
2  [0.360526136814407]  [-4.90092139925902e-5]   [1.06974105670843e-5]   
3  [0.360542952948320]  [-3.37979061723059e-5]   [2.59256483275405e-5]   
4  [0.360539595583605]  [-3.10195483303466e-5]   [2.26657518484497e-5]   

            (y*-y_n)(0.5)  
0   [0.00135724715734692]  
1  [-4.37401142189264e-5]  
2  [-2.61368144066076e-5]  
3  [-4.29529483196855e-5]  
4  [-3.95955836050566e-5]

<h5>Функция поиска узлов многочлена Чебышева первого рода</h5>

In [135]:
def jacobiKnots(n):
    res = []
    for i in range(1, n+1):
        res.append(math.cos(math.pi*(2*i-1)/(2*n)))
    return res

<h5>Функция для нахождения коэффициентов расширенной матрицы A метода Коллокации</h5>

In [140]:
def collocMatrixCoeff(n, coordFunctions, L):
    x = sp.Symbol("x")
    A = np.zeros((n, n))
    b = np.zeros((n, 1))
    t = jacobiKnots(n)
    for i in range(n):
        for j in range(n):
            A[i,j] = L[j].subs(x, t[i])
        b[i] = sp.simplify(1+t[i]/3)
    return [A, b]

<h5>Функция для генерации ЛНЗ системы координатных функций</h5>

In [58]:
def createcoordFunctions(n):
    x = sp.Symbol("x")
    res = [sp.simplify(1-sp.Pow(x, 2)), sp.expand(2*x*(1-sp.Pow(x, 2)))]
    diff = [sp.diff(res[0], x), sp.diff(res[1], x)]
    p = [sp.simplify(1), sp.simplify(2*x)]
    for i in range(0, n-2):
        u = sp.expand(( (i+3)*(2*i+5)*x*p[i+1] - (i+3)*(i+2)*p[i] )/( (i+4)*(i + 2) ))
        p.append(u)
        res.append(sp.simplify((1-sp.Pow(x, 2))*p[i+2]))
        diff.append(sp.simplify(sp.diff(res[i+2], x)))
    return [res, diff]

<h5>Функция для нахождения коэффициентов расширенной матрицы A метода Галеркина</h5>

In [137]:
def matrixCoeff(n, coordFunctions, L):
    x = sp.Symbol("x")
    A = np.zeros((n, n))
    b = np.zeros((n, 1))
    for i in range(n):
        for j in range(n):
            A[i,j] = scalMultiply(L[j], coordFunctions[i])
        b[i] = scalMultiply(sp.simplify(1+x/3), coordFunctions[i])
    return [A, b]

<h5>Функция для нахождения скалярного произведения в $L_{2}$</h5>

In [104]:
def scalMultiply(a, b):
    x = sp.Symbol("x")
    f = sp.integrate(sp.nsimplify(a*b), (x, -1, 1))
    return f

<h5>Функция для нахождения коэффициентов типа $(L\omega_{j})$ </h5>

In [212]:
def countL(coordFunctions, diffCoordFunctions):
    res = []
    for i in range(7):
        secondDiff = sp.simplify(sp.diff(diffCoordFunctions[i], x))
        res.append(sp.simplify(-((4-x)/(5-2*x))*secondDiff + ((1-x)/(2))*diffCoordFunctions[i]+(1/2)*coordFunctions[i]*sp.ln(3+x)))
    return res

<h5>Функция для решения СЛАУ $\sum\limits_{j=1}^n a_{ij}c_{j} = f_{i}$, $i = 1, 2, \dots, n$ </h5>

In [95]:
def countCoeff(A, b, n):
    c = np.linalg.solve(A[:n, :n], b[:n,:1])
    return c